Added sarif.yaml

diff --git a/.github/workflows/sarif.yml b/.github/workflows/sarif.yml
--- a/.github/workflows/sarif.yml
+++ b/.github/workflows/sarif.yml
@@ -52,3 +52,27 @@ jobs:
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: cx_result.sarif
+
+      - name: Verify cx_result.sarif
+        run: |
+          if [ -f cx_result.sarif ]; then
+            echo "✔ cx_result.sarif exists!"
+            ls -lh cx_result.sarif
+          else
+            echo "❌ cx_result.sarif NOT found!"
+            exit 1
+          fi
+
+      - name: Show SARIF header
+        run: head -n 20 cx_result.sarif
+
+      - name: Upload XML Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: cx_result.sarif
+          path: cx_result.sarif
+
+      - name: Upload Checkmarx SARIF report
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: cx_result.sarif
